TblUsers:
    type: entity
    table: tbl_users
    indexes:
        fk_users_countries_idx:
            columns:
                - id_country
        fk_users_departments_idx:
            columns:
                - id_dept
    uniqueConstraints:
        id_document_UNIQUE:
            columns:
                - id_document
        UNIQ_BAE7EFF692FC23A8:
            columns:
                - username_canonical
        UNIQ_BAE7EFF6A0D96FBF:
            columns:
                - email_canonical
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        username:
            type: string
            nullable: false
            length: 255
            fixed: false
        firstName:
            type: string
            nullable: false
            length: 20
            fixed: false
            column: first_name
        secondName:
            type: string
            nullable: true
            length: 20
            fixed: false
            column: second_name
        thirdName:
            type: string
            nullable: true
            length: 20
            fixed: false
            column: third_name
        firstLastname:
            type: string
            nullable: false
            length: 20
            fixed: false
            column: first_lastname
        secondLastname:
            type: string
            nullable: true
            length: 20
            fixed: false
            column: second_lastname
        marriageLastname:
            type: string
            nullable: true
            length: 20
            fixed: false
            column: marriage_lastname
        idDocument:
            type: bigint
            nullable: false
            unsigned: false
            column: id_document
        gender:
            type: string
            nullable: false
            length: 2
            fixed: false
        maritalStatus:
            type: string
            nullable: false
            length: 45
            fixed: false
            column: marital_status
        email:
            type: string
            nullable: false
            length: 255
            fixed: false
        phoneNumber:
            type: integer
            nullable: true
            unsigned: false
            column: phone_number
        cellphoneNumber:
            type: integer
            nullable: false
            unsigned: false
            column: cellphone_number
        usernameCanonical:
            type: string
            nullable: false
            length: 255
            fixed: false
            column: username_canonical
        emailCanonical:
            type: string
            nullable: false
            length: 255
            fixed: false
            column: email_canonical
        enabled:
            type: boolean
            nullable: false
        salt:
            type: string
            nullable: false
            length: 255
            fixed: false
        password:
            type: string
            nullable: false
            length: 255
            fixed: false
        lastLogin:
            type: datetime
            nullable: true
            column: last_login
        locked:
            type: boolean
            nullable: false
        expired:
            type: boolean
            nullable: false
        expiresAt:
            type: datetime
            nullable: true
            column: expires_at
        confirmationToken:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: confirmation_token
        passwordRequestedAt:
            type: datetime
            nullable: true
            column: password_requested_at
        roles:
            type: array
            nullable: false
            length: null
            fixed: false
        credentialsExpired:
            type: boolean
            nullable: false
            column: credentials_expired
        credentialsExpireAt:
            type: datetime
            nullable: true
            column: credentials_expire_at
    manyToOne:
        idCountry:
            targetEntity: TblCountries
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_country:
                    referencedColumnName: id_country
            orphanRemoval: false
        idDept:
            targetEntity: TblDepartments
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_dept:
                    referencedColumnName: id_dept
            orphanRemoval: false
    lifecycleCallbacks: {  }
