users_index:
    path:     /
    defaults: { _controller: "MainBundle:TblUsers:index" }
    methods:  GET

users_show:
    path:     /{id}/show
    defaults: { _controller: "MainBundle:TblUsers:show" }
    methods:  GET

users_new:
    path:     /new
    defaults: { _controller: "MainBundle:TblUsers:new" }
    methods:  [GET, POST]

users_edit:
    path:     /{id}/edit
    defaults: { _controller: "MainBundle:TblUsers:edit" }
    methods:  [GET, POST]

users_delete:
    path:     /{id}/delete
    defaults: { _controller: "MainBundle:TblUsers:delete" }
    methods:  DELETE
